// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDB() {
  return window['go']['main']['App']['CheckDB']();
}

export function CreateCartItem(arg1) {
  return window['go']['main']['App']['CreateCartItem'](arg1);
}

export function CreateCategory(arg1) {
  return window['go']['main']['App']['CreateCategory'](arg1);
}

export function CreateDelivery(arg1) {
  return window['go']['main']['App']['CreateDelivery'](arg1);
}

export function CreateInvoiceIn(arg1) {
  return window['go']['main']['App']['CreateInvoiceIn'](arg1);
}

export function CreateInvoiceOut(arg1) {
  return window['go']['main']['App']['CreateInvoiceOut'](arg1);
}

export function CreateOrder(arg1) {
  return window['go']['main']['App']['CreateOrder'](arg1);
}

export function CreateOrderItem(arg1) {
  return window['go']['main']['App']['CreateOrderItem'](arg1);
}

export function CreateProduct(arg1) {
  return window['go']['main']['App']['CreateProduct'](arg1);
}

export function CreateProductImage(arg1) {
  return window['go']['main']['App']['CreateProductImage'](arg1);
}

export function CreateReceipt(arg1) {
  return window['go']['main']['App']['CreateReceipt'](arg1);
}

export function CreateRecord(arg1, arg2) {
  return window['go']['main']['App']['CreateRecord'](arg1, arg2);
}

export function CreateReview(arg1) {
  return window['go']['main']['App']['CreateReview'](arg1);
}

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function CreateWishlist(arg1) {
  return window['go']['main']['App']['CreateWishlist'](arg1);
}

export function DeleteCartItem(arg1) {
  return window['go']['main']['App']['DeleteCartItem'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteDelivery(arg1) {
  return window['go']['main']['App']['DeleteDelivery'](arg1);
}

export function DeleteInvoiceIn(arg1) {
  return window['go']['main']['App']['DeleteInvoiceIn'](arg1);
}

export function DeleteInvoiceOut(arg1) {
  return window['go']['main']['App']['DeleteInvoiceOut'](arg1);
}

export function DeleteOrder(arg1) {
  return window['go']['main']['App']['DeleteOrder'](arg1);
}

export function DeleteOrderItem(arg1) {
  return window['go']['main']['App']['DeleteOrderItem'](arg1);
}

export function DeleteProduct(arg1) {
  return window['go']['main']['App']['DeleteProduct'](arg1);
}

export function DeleteProductImage(arg1) {
  return window['go']['main']['App']['DeleteProductImage'](arg1);
}

export function DeleteReceipt(arg1) {
  return window['go']['main']['App']['DeleteReceipt'](arg1);
}

export function DeleteReview(arg1) {
  return window['go']['main']['App']['DeleteReview'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function DeleteWishlist(arg1) {
  return window['go']['main']['App']['DeleteWishlist'](arg1);
}

export function ExportInvoiceWithTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportInvoiceWithTemplate'](arg1, arg2, arg3);
}

export function GenerateOrderNumber() {
  return window['go']['main']['App']['GenerateOrderNumber']();
}

export function GetCartItem(arg1) {
  return window['go']['main']['App']['GetCartItem'](arg1);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetCategory(arg1) {
  return window['go']['main']['App']['GetCategory'](arg1);
}

export function GetDelivery(arg1) {
  return window['go']['main']['App']['GetDelivery'](arg1);
}

export function GetFormFields(arg1) {
  return window['go']['main']['App']['GetFormFields'](arg1);
}

export function GetInvoiceIn(arg1) {
  return window['go']['main']['App']['GetInvoiceIn'](arg1);
}

export function GetInvoiceOut(arg1) {
  return window['go']['main']['App']['GetInvoiceOut'](arg1);
}

export function GetOrder(arg1) {
  return window['go']['main']['App']['GetOrder'](arg1);
}

export function GetOrderItem(arg1) {
  return window['go']['main']['App']['GetOrderItem'](arg1);
}

export function GetProduct(arg1) {
  return window['go']['main']['App']['GetProduct'](arg1);
}

export function GetProductImage(arg1) {
  return window['go']['main']['App']['GetProductImage'](arg1);
}

export function GetReceipt(arg1) {
  return window['go']['main']['App']['GetReceipt'](arg1);
}

export function GetRecord(arg1, arg2) {
  return window['go']['main']['App']['GetRecord'](arg1, arg2);
}

export function GetReportData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetReportData'](arg1, arg2, arg3);
}

export function GetReview(arg1) {
  return window['go']['main']['App']['GetReview'](arg1);
}

export function GetTableData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTableData'](arg1, arg2, arg3, arg4);
}

export function GetTables() {
  return window['go']['main']['App']['GetTables']();
}

export function GetUser(arg1) {
  return window['go']['main']['App']['GetUser'](arg1);
}

export function GetWishlist(arg1) {
  return window['go']['main']['App']['GetWishlist'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function ReadFileBase64(arg1) {
  return window['go']['main']['App']['ReadFileBase64'](arg1);
}

export function SearchCartItems(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchCartItems'](arg1, arg2, arg3);
}

export function SearchInvoiceIn(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchInvoiceIn'](arg1, arg2, arg3);
}

export function SearchInvoiceOut(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchInvoiceOut'](arg1, arg2, arg3);
}

export function SearchOrderItems(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchOrderItems'](arg1, arg2, arg3);
}

export function SearchOrders(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchOrders'](arg1, arg2, arg3);
}

export function SearchReceipt(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchReceipt'](arg1, arg2, arg3);
}

export function SearchReviews(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchReviews'](arg1, arg2, arg3);
}

export function SearchWishlist(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchWishlist'](arg1, arg2, arg3);
}

export function UpdateCartItem(arg1, arg2) {
  return window['go']['main']['App']['UpdateCartItem'](arg1, arg2);
}

export function UpdateCategory(arg1, arg2) {
  return window['go']['main']['App']['UpdateCategory'](arg1, arg2);
}

export function UpdateDelivery(arg1, arg2) {
  return window['go']['main']['App']['UpdateDelivery'](arg1, arg2);
}

export function UpdateInvoiceIn(arg1, arg2) {
  return window['go']['main']['App']['UpdateInvoiceIn'](arg1, arg2);
}

export function UpdateInvoiceOut(arg1, arg2) {
  return window['go']['main']['App']['UpdateInvoiceOut'](arg1, arg2);
}

export function UpdateOrder(arg1, arg2) {
  return window['go']['main']['App']['UpdateOrder'](arg1, arg2);
}

export function UpdateOrderItem(arg1, arg2) {
  return window['go']['main']['App']['UpdateOrderItem'](arg1, arg2);
}

export function UpdateProduct(arg1, arg2) {
  return window['go']['main']['App']['UpdateProduct'](arg1, arg2);
}

export function UpdateProductImage(arg1, arg2) {
  return window['go']['main']['App']['UpdateProductImage'](arg1, arg2);
}

export function UpdateReceipt(arg1, arg2) {
  return window['go']['main']['App']['UpdateReceipt'](arg1, arg2);
}

export function UpdateRecord(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateRecord'](arg1, arg2, arg3);
}

export function UpdateReview(arg1, arg2) {
  return window['go']['main']['App']['UpdateReview'](arg1, arg2);
}

export function UpdateUser(arg1, arg2) {
  return window['go']['main']['App']['UpdateUser'](arg1, arg2);
}

export function UpdateWishlist(arg1, arg2) {
  return window['go']['main']['App']['UpdateWishlist'](arg1, arg2);
}
