// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDB():Promise<boolean>;

export function CreateCartItem(arg1:Record<string, any>):Promise<Record<string, any>>;

export function CreateCategory(arg1:Record<string, any>):Promise<Record<string, any>>;

export function CreateDelivery(arg1:Record<string, any>):Promise<Record<string, any>>;

export function CreateInvoiceIn(arg1:Record<string, any>):Promise<Record<string, any>>;

export function CreateInvoiceOut(arg1:Record<string, any>):Promise<Record<string, any>>;

export function CreateOrder(arg1:Record<string, any>):Promise<Record<string, any>>;

export function CreateOrderItem(arg1:Record<string, any>):Promise<Record<string, any>>;

export function CreateProduct(arg1:Record<string, any>):Promise<Record<string, any>>;

export function CreateProductImage(arg1:Record<string, any>):Promise<Record<string, any>>;

export function CreateReceipt(arg1:Record<string, any>):Promise<Record<string, any>>;

export function CreateRecord(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;

export function CreateReview(arg1:Record<string, any>):Promise<Record<string, any>>;

export function CreateUser(arg1:Record<string, any>):Promise<Record<string, any>>;

export function CreateWishlist(arg1:Record<string, any>):Promise<Record<string, any>>;

export function DeleteCartItem(arg1:number):Promise<Record<string, any>>;

export function DeleteCategory(arg1:number):Promise<Record<string, any>>;

export function DeleteDelivery(arg1:number):Promise<Record<string, any>>;

export function DeleteInvoiceIn(arg1:number):Promise<Record<string, any>>;

export function DeleteInvoiceOut(arg1:number):Promise<Record<string, any>>;

export function DeleteOrder(arg1:number):Promise<Record<string, any>>;

export function DeleteOrderItem(arg1:number):Promise<Record<string, any>>;

export function DeleteProduct(arg1:number):Promise<Record<string, any>>;

export function DeleteProductImage(arg1:number):Promise<Record<string, any>>;

export function DeleteReceipt(arg1:number):Promise<Record<string, any>>;

export function DeleteReview(arg1:number):Promise<Record<string, any>>;

export function DeleteUser(arg1:number):Promise<Record<string, any>>;

export function DeleteWishlist(arg1:number):Promise<Record<string, any>>;

export function ExportInvoiceWithTemplate(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GenerateOrderNumber():Promise<string>;

export function GenerateReceiptPDF(arg1:number):Promise<string>;

export function GetCartItem(arg1:number):Promise<Record<string, any>>;

export function GetCategories():Promise<Array<Record<string, any>>>;

export function GetCategory(arg1:number):Promise<Record<string, any>>;

export function GetDelivery(arg1:number):Promise<Record<string, any>>;

export function GetFormFields(arg1:string):Promise<Array<Record<string, any>>>;

export function GetInvoiceIn(arg1:number):Promise<Record<string, any>>;

export function GetInvoiceOut(arg1:number):Promise<Record<string, any>>;

export function GetOrder(arg1:number):Promise<Record<string, any>>;

export function GetOrderItem(arg1:number):Promise<Record<string, any>>;

export function GetOrderTotal(arg1:number):Promise<number>;

export function GetProduct(arg1:number):Promise<Record<string, any>>;

export function GetProductImage(arg1:number):Promise<Record<string, any>>;

export function GetReceipt(arg1:number):Promise<Record<string, any>>;

export function GetRecord(arg1:string,arg2:number):Promise<Record<string, any>>;

export function GetReportData(arg1:string,arg2:string,arg3:string):Promise<Array<Record<string, any>>>;

export function GetReview(arg1:number):Promise<Record<string, any>>;

export function GetTableData(arg1:string,arg2:number,arg3:string,arg4:number):Promise<Record<string, any>>;

export function GetTables():Promise<Array<string>>;

export function GetUser(arg1:number):Promise<Record<string, any>>;

export function GetWishlist(arg1:number):Promise<Record<string, any>>;

export function Login(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function SearchCartItems(arg1:number,arg2:string,arg3:number):Promise<Record<string, any>>;

export function SearchInvoiceIn(arg1:number,arg2:string,arg3:number):Promise<Record<string, any>>;

export function SearchInvoiceOut(arg1:number,arg2:string,arg3:number):Promise<Record<string, any>>;

export function SearchOrderItems(arg1:number,arg2:string,arg3:number):Promise<Record<string, any>>;

export function SearchOrders(arg1:number,arg2:string,arg3:number):Promise<Record<string, any>>;

export function SearchReceipt(arg1:number,arg2:string,arg3:number):Promise<Record<string, any>>;

export function SearchReviews(arg1:number,arg2:string,arg3:number):Promise<Record<string, any>>;

export function SearchWishlist(arg1:number,arg2:string,arg3:number):Promise<Record<string, any>>;

export function UpdateCartItem(arg1:number,arg2:Record<string, any>):Promise<Record<string, any>>;

export function UpdateCategory(arg1:number,arg2:Record<string, any>):Promise<Record<string, any>>;

export function UpdateDelivery(arg1:number,arg2:Record<string, any>):Promise<Record<string, any>>;

export function UpdateInvoiceIn(arg1:number,arg2:Record<string, any>):Promise<Record<string, any>>;

export function UpdateInvoiceOut(arg1:number,arg2:Record<string, any>):Promise<Record<string, any>>;

export function UpdateOrder(arg1:number,arg2:Record<string, any>):Promise<Record<string, any>>;

export function UpdateOrderItem(arg1:number,arg2:Record<string, any>):Promise<Record<string, any>>;

export function UpdateProduct(arg1:number,arg2:Record<string, any>):Promise<Record<string, any>>;

export function UpdateProductImage(arg1:number,arg2:Record<string, any>):Promise<Record<string, any>>;

export function UpdateReceipt(arg1:number,arg2:Record<string, any>):Promise<Record<string, any>>;

export function UpdateRecord(arg1:string,arg2:number,arg3:Record<string, any>):Promise<Record<string, any>>;

export function UpdateReview(arg1:number,arg2:Record<string, any>):Promise<Record<string, any>>;

export function UpdateUser(arg1:number,arg2:Record<string, any>):Promise<Record<string, any>>;

export function UpdateWishlist(arg1:number,arg2:Record<string, any>):Promise<Record<string, any>>;
